### ISSUE TITLE
Default Values of Helm Chart result in Invalid License

### ISSUE THREAD

**Issue by AliveDevil** [kerberos-io/helm-charts#17]
With this configuration
https://github.com/kerberos-io/helm-charts/blob/db96c2a2032fdb90c070c36baf352bc7f7e1b2b3/charts/hub/values.yaml#L139-L141
the provided 8-camera license isn't accepted, and kerberos/hub-api:1.0.1391608878 is months old.

**Comment by cedricve** [comment]
The license has been updated, we have changed the signing mechanism. Apologies for that, let us know if works now. ;)

**Comment by AliveDevil** [comment]
Thank you for the quick resolution.
I'm evaluating some surveillance solutions, and don't want to use Kubernetes, but some dedicated VMs with manually created Podman containers, so might take a hot minute, before I can check this works.

**Comment by cedricve** [comment]
No problem thank you for the response @AliveDevil! Have a great weekend.

**Comment by cedricve** [comment]
This is fixed. Closing for now
